const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/HoSheil/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.FIXTURE_URL||'http://127.0.0.1:64335/artifacts/trace-worksite-v1-20260915/ui/fixture.html';
const executablePath=process.env.CHROMIUM_PATH||'D:/AGeneral Workspace/xjch2026/wshuzhilv/.playwright-browsers/chromium-1234/chrome-win64/chrome.exe';
const dir=__dirname,prefix=process.argv[2]||'first';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath});
 const context=await browser.newContext({viewport:{width:1672,height:941},reducedMotion:'reduce'});
 const page=await context.newPage();
 const errors=[],responses=[],checks=[],renders=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('response',response=>{if(response.status()>=400)responses.push({status:response.status(),url:response.url()});});
 const check=async(name,fn)=>{try{await fn();checks.push({name,pass:true});}catch(error){checks.push({name,pass:false,error:error.message});}};
 const click=action=>page.locator(`[data-action="${action}"]:visible`).first().click();
 const view=()=>page.evaluate(()=>window.worksiteFixture.view);
 await page.goto(base);await page.waitForFunction(()=>window.worksiteFixture);await page.evaluate(()=>document.fonts.ready);
 // One narrow end-to-end path first: source -> actual effect -> discovery -> result.
 await check('overview → intake opens selected snapshot',async()=>{await click('open-intake');assert.equal((await view()).screen,'intake');assert.match(await page.locator('[data-text="source-text"]').innerText(),/可以先保存/);});
 await check('exclude changes actual context, not merely button state',async()=>{await page.locator('[data-role="exclude"]').click();const value=await view();assert(!value.contextIntakeIds.includes(value.selectedIntakeId));assert.match(await page.locator('[data-text="context-instruction"]').innerText(),/不再进入/);});
 await check('contrast emits distinct instruction',async()=>{await page.locator('[data-role="contrast"]').click();const value=await view();assert.equal(value.selectedIntake.role,'contrast');assert(value.context.find(item=>item.id===value.selectedIntakeId).instruction.includes('比较条件和差异'));assert.match(await page.locator('[data-text="context-instruction"]').innerText(),/不据此约束当前实现/);});
 await check('intake → impact keeps independent usage unconfirmed',async()=>{await click('impact');const value=await view();assert.equal(value.screen,'impact');assert.equal(value.impact.stages.usage,false);assert.equal(await page.locator('[data-stage="usage"]').getAttribute('data-confirmed'),'false');});
 await check('artifact does not fake external link',async()=>{await click('artifact');assert.match(await page.locator('.worksite-notice').innerText(),/尚未连接/);assert.equal(context.pages().length,1);});
 await check('impact correction is retained without erasing evidence',async()=>{const before=(await view()).impact.evidence.length;await click('correction');await page.locator('[data-local-field="correction"]').fill('这只是可选字段，不代表已经恢复现场。');await click('save-correction');const value=await view();assert.equal(value.impact.relation,'disputed');assert.equal(value.impact.evidence.length,before);assert.match(value.impact.correction,/可选字段/);});
 await check('capture opens real literal discovery',async()=>{await click('overview');await page.locator('[data-field="composer"]').fill('输入 <img src=x onerror=alert(1)> 仍是原话');await page.locator('[data-submit="capture"]').click();assert.equal((await view()).screen,'finding');assert.match(await page.locator('[data-field="finding-text"]').inputValue(),/<img/);assert.equal(await page.locator('img[src="x"]').count(),0);});
 await check('reject association keeps original discovery and source',async()=>{const before=(await view()).finding;await click('unlink-finding');const value=await view();assert.equal(value.finding.relation,'unrelated');assert.equal(value.finding.text,before.text);assert.deepEqual(value.finding.source,before.source);});
 await check('rejected association can be explicitly reselected',async()=>{const before=(await view()).finding.text;await click('link-finding');assert(await page.locator('.worksite-panel').isVisible());await page.evaluate(()=>window.worksiteFixture.dispatch({type:'CLEAR_NOTICE'}));await page.locator('[data-action="choose-finding-matter"]').first().click();assert.equal((await view()).finding.relation,'linked');assert.equal((await view()).finding.text,before);});
 await check('keep and use discovery only in this work',async()=>{await click('keep-finding');await click('use-finding');const value=await view();assert(value.finding.saved);assert(value.finding.useInCurrentWork);assert.equal(value.contextFindings.length,1);assert.match(await page.locator('[data-text="finding-receipt"]').innerText(),/未发送/);});
 await check('result navigation does not fabricate facts',async()=>{await click('overview');await click('results');const value=await view();assert.equal(value.result.fact,'');assert.equal(value.receipt,null);assert(await page.locator('[data-action="review"]').isDisabled());});
 await check('keep result does not modify understanding',async()=>{const before=(await view()).matters[0].understanding;await page.locator('[data-field="result-fact"]').fill('两天后回看原文，想起了当时的问题。');await page.locator('[data-field="result-proposed"]').fill('先保留可恢复现场的信息，附言可以之后补。');await click('keep-result');assert.equal((await view()).matters[0].understanding,before);assert.equal((await view()).result.decision,'result-only');});
 await check('review opens before/after without implicit revision',async()=>{const before=(await view()).matters[0].understanding;await click('review');assert(await page.locator('.worksite-review').isVisible());assert.equal((await view()).matters[0].understanding,before);await page.locator('[data-field="review-after"]').fill('保留可恢复现场的信息；必要时再补个人附言。');});
 await check('explicit revision → undo retains original result',async()=>{await click('confirm-review');const revised=await view();assert.equal(revised.matters[0].understanding,'保留可恢复现场的信息；必要时再补个人附言。');assert(revised.receipt);await click('undo');const undone=await view();assert(undone.receipt.undone);assert.equal(undone.result.fact,revised.result.fact);assert(undone.matters[0].version>revised.matters[0].version);});
 await check('switch work isolates drafts, then restores first work',async()=>{await click('switch');await page.locator('[data-action="select-work"]').nth(1).click();assert.equal((await view()).result.fact,'');await click('switch');await page.locator('[data-action="select-work"]').nth(0).click();assert.match((await view()).result.fact,/两天后/);});
 await check('IME and caret survive view updates without DOM replacement',async()=>{await page.evaluate(()=>window.worksiteFixture.reset('finding'));const input=page.locator('[data-field="finding-text"]');await input.focus();await input.evaluate(el=>{window.testInput=el;el.value='正在输入中文';el.setSelectionRange(2,4);el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await page.evaluate(()=>window.worksiteFixture.dispatch({type:'CLEAR_NOTICE'}));assert(await input.evaluate(el=>el===window.testInput&&el.selectionStart===2&&el.selectionEnd===4&&el.value==='正在输入中文'));await input.evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));assert.equal((await view()).finding.text,'正在输入中文');});
 await check('Escape closes local panel and returns focus',async()=>{await click('switch');assert(await page.locator('.worksite-panel').isVisible());await page.keyboard.press('Escape');assert(await page.locator('.worksite-panel').isHidden());assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'switch');});
 await check('empty capture is disabled and Enter does not submit composition',async()=>{await page.evaluate(()=>window.worksiteFixture.reset('overview'));assert(await page.locator('[data-submit="capture"]').isDisabled());await page.locator('[data-field="composer"]').evaluate(el=>{el.focus();el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,key:'Enter',isComposing:true}));el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));});assert.equal((await view()).screen,'overview');});
 await check('external Agent does not pretend integration',async()=>{await click('agent');assert.match(await page.locator('.worksite-notice').innerText(),/尚未连接外部 Agent/);});
 await check('review keyboard focus is contained and Escape cancels',async()=>{await page.evaluate(()=>window.worksiteFixture.reset('results'));await click('review');await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.closest('.worksite-review')!==null));await page.keyboard.press('Shift+Tab');assert(await page.evaluate(()=>document.activeElement.closest('.worksite-review')!==null));await page.keyboard.press('Escape');assert.equal((await view()).review.open,false);assert.equal((await view()).receipt,null);});
 await check('large text remains editable and complete',async()=>{const large='这是长文输入，原话不会被组件截断。'.repeat(90);await page.locator('[data-field="result-fact"]').fill(large);assert.equal((await view()).result.fact,large);assert.equal(await page.locator('[data-field="result-fact"]').inputValue(),large);assert(await page.locator('[data-field="result-fact"]').evaluate(el=>el.scrollHeight>el.clientHeight));});
 await check('interrupted bird transition finishes in final state',async()=>{await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{window.worksiteFixture.reset('overview');window.worksiteFixture.dispatch({type:'NAVIGATE',screen:'intake'});window.worksiteFixture.dispatch({type:'NAVIGATE',screen:'impact'});window.worksiteFixture.dispatch({type:'NAVIGATE',screen:'results'});});await page.waitForTimeout(900);assert.equal((await view()).screen,'results');assert.equal(await page.locator('.worksite-flying').count(),0);await page.emulateMedia({reducedMotion:'reduce'});});
 await check('glass surface unfolds from clicked source and interruption cleans transform',async()=>{await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>window.worksiteFixture.reset('overview'));await click('open-intake');await page.waitForTimeout(75);assert.notEqual(await page.locator('[data-surface="intake-detail"]').evaluate(el=>el.style.transform),'');await page.evaluate(()=>window.worksiteFixture.dispatch({type:'NAVIGATE',screen:'impact'}));assert.equal(await page.locator('[data-surface="intake-detail"]').evaluate(el=>el.style.transform),'');await page.waitForTimeout(700);await page.emulateMedia({reducedMotion:'reduce'});});
 await check('narrow results retain reachable confirmation controls',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.worksiteFixture.reset('results'));await page.locator('[data-action="review"]').scrollIntoViewIfNeeded();await click('review');assert(await page.locator('.worksite-review').isVisible());assert(await page.locator('[data-action="confirm-review"]').isEnabled());await click('cancel-review');assert.equal(await page.evaluate(()=>document.querySelector('.worksite-viewport').scrollWidth>document.querySelector('.worksite-viewport').clientWidth+1),false);await page.setViewportSize({width:1672,height:941});});
 // Single batched visual inspection: all five desktop states + narrow finding/results + empty.
 for(const [screen,width,height] of (process.env.NO_VISUAL==='1'?[]:[['overview',1672,941],['intake',1672,941],['impact',1672,941],['finding',1672,941],['results',1672,941],['finding',880,720],['results',390,844],['empty',1672,941]])){
   await page.setViewportSize({width,height});await page.evaluate(screen=>window.worksiteFixture.reset(screen),screen);await page.waitForTimeout(500);await page.evaluate(()=>document.fonts.ready);
   const file=`${prefix}-${screen}-${width}.png`;await page.screenshot({path:path.join(dir,file),fullPage:false});
   renders.push({screen,width,height,file,...await page.evaluate(()=>({fonts:[...document.fonts].map(f=>({family:f.family,status:f.status})),images:[...document.querySelectorAll('.worksite-root img')].map(img=>({source:img.getAttribute('src'),complete:img.complete,width:img.naturalWidth})),horizontalOverflow:document.querySelector('.worksite-viewport').scrollWidth>document.querySelector('.worksite-viewport').clientWidth+1,material:[...document.querySelectorAll('[data-refraction]')].map(el=>el.dataset.refraction),panels:[...document.querySelectorAll('.worksite-state:not([hidden]) .worksite-surface')].filter(el=>!el.hidden).map(el=>({name:el.dataset.surface,clientHeight:el.clientHeight,scrollHeight:el.scrollHeight})),visibleText:document.querySelector('.worksite-state:not([hidden])').innerText}))});
 }
 await check('all requested assets and fonts loaded',async()=>{assert.equal(responses.length,0);for(const render of renders){assert(render.fonts.every(f=>f.status==='loaded'));assert(render.images.every(img=>img.complete&&img.width>0));}});
 await check('no uncaught browser errors',async()=>assert.equal(errors.length,0));
 const result={taskId:'trace-worksite-v1-20260915',at:new Date().toISOString(),prefix,base,checks,passed:checks.filter(c=>c.pass).length,total:checks.length,errors,responses,renders};
 fs.writeFileSync(path.join(dir,`${prefix}-checks.json`),JSON.stringify(result,null,2));
 console.log(JSON.stringify({passed:result.passed,total:result.total,failed:checks.filter(c=>!c.pass),errors,responses,renders:renders.map(({visibleText,...value})=>value)},null,2));
 await browser.close();if(result.passed!==result.total)process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1;});
