/* Run from any cwd. Own ephemeral loopback server + isolated Chromium; both close in finally. */
const {createServer}=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {createHash}=require('node:crypto');
const {chromium}=require('C:/Users/HoSheil/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const WORKSPACE=path.resolve(__dirname,'../../..');
const CHROME='D:/AGeneral Workspace/xjch2026/wshuzhilv/.playwright-browsers/chromium-1234/chrome-win64/chrome.exe';
const prefix=process.argv[2]||'first';
const capture=!process.argv.includes('--no-screenshots');
const output=path.join(__dirname,'checks');fs.mkdirSync(output,{recursive:true});
const report={taskId:'trace-compare-v1-20260915',scope:'isolated native DOM module + pure fixture host; not integrated app',prefix,checks:[],errors:[],badResponses:[],screens:[],serverStopped:false};
report.inputs=Object.fromEntries(['comparison-screen.mjs','comparison.css','fixture.mjs','../model/comparison-model.mjs','../images/ready/compare-environment.png','../fonts/derived/TraceCompareSans-fixed.woff2','../fonts/derived/TraceCompareSerif-fixed.woff2'].map(file=>[file,createHash('sha256').update(fs.readFileSync(path.join(__dirname,file))).digest('hex')]));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.png':'image/png','.woff2':'font/woff2','.woff':'font/woff'};
const server=createServer((req,res)=>{let target;try{target=path.resolve(WORKSPACE,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));}catch{res.writeHead(400);res.end();return;}if(!target.startsWith(WORKSPACE+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(target,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(target)]||'application/octet-stream');res.end(data);});});
let browser;
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 report.port=server.address().port;
 const base=`http://127.0.0.1:${report.port}/artifacts/trace-compare-v1-20260915/ui/fixture.html`;
 browser=await chromium.launch({executablePath:CHROME,headless:true});
 const page=await browser.newPage({viewport:{width:1672,height:941},reducedMotion:'reduce'});
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.badResponses.push({url:r.url(),status:r.status()});});
 await page.goto(base);await page.waitForFunction(()=>!!window.compareFixture);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(800);
 async function reset(screen){await page.evaluate(s=>window.compareFixture.reset(s),screen);await page.waitForTimeout(220);}
 async function check(name,fn){try{await fn();report.checks.push({name,ok:true});}catch(error){report.checks.push({name,ok:false,error:error.message});}}
 async function view(){return page.evaluate(()=>window.compareFixture.view);}
 async function host(){return page.evaluate(()=>window.compareFixture.host);}
 for(const mode of ['search','candidates','compare','returned']){
  await reset(mode);if(capture)await page.screenshot({path:path.join(output,`${prefix}-${mode}.png`)});
  report.screens.push(await page.evaluate(()=>({screen:window.compareFixture.view.screen,fontSans:document.fonts.check('700 24px "Trace Compare Sans"'),fontSerif:document.fonts.check('600 24px "Trace Compare Serif"'),images:[...document.querySelectorAll('img')].map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0})),glass:[...document.querySelectorAll('[data-refraction]')].map(e=>e.dataset.refraction),horizontalOverflow:document.getElementById('app').scrollWidth>document.getElementById('app').clientWidth+1,clippedButtons:[...document.querySelectorAll('button')].filter(e=>{const r=e.getBoundingClientRect();const p=e.closest('.compare-candidate,.compare-search-form,.compare-reading');const b=p?.getBoundingClientRect();return b&&r.height&&r.bottom>b.bottom+1;}).map(e=>e.textContent)})));
 }
 await check('All four screens load fonts/assets without horizontal overflow or clipped buttons',async()=>{assert(report.screens.every(s=>s.fontSans&&s.fontSerif&&!s.horizontalOverflow&&s.clippedButtons.length===0&&s.images.every(i=>i.loaded)),'visual geometry/assets check failed');});
 await check('Search begins with no candidates; SEARCH produces exactly 3 local demos',async()=>{await reset('search');assert((await view()).candidates.length===0,'pre-search candidates leaked');await page.click('[data-search-submit]');const v=await view();assert(v.screen==='candidates'&&v.candidates.length===3&&v.search.isDemo,'wrong search output');});
 await check('Query update preserves same input node and selection',async()=>{await reset('search');const result=await page.evaluate(()=>{const input=document.querySelector('[data-field="question"]');input.focus();input.value='这是一个精确的问题';input.setSelectionRange(3,6);input.dispatchEvent(new Event('input',{bubbles:true}));return {same:input===document.querySelector('[data-field="question"]'),start:input.selectionStart,end:input.selectionEnd,active:document.activeElement===input,value:window.compareFixture.view.query.question};});assert(result.same&&result.active&&result.start===3&&result.end===6&&result.value==='这是一个精确的问题','input/selection changed');});
 await check('IME composition does not dispatch partial business text',async()=>{await reset('search');const result=await page.evaluate(()=>{const el=document.querySelector('[data-field="question"]');el.focus();const before=window.compareFixture.view.query.question;el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.value='正在输入';el.dispatchEvent(new Event('input',{bubbles:true}));const during=window.compareFixture.view.query.question;el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'正在输入'}));return{before,during,after:window.compareFixture.view.query.question,same:el===document.querySelector('[data-field="question"]')};});assert(result.before===result.during&&result.after==='正在输入'&&result.same,'partial IME text dispatched or input replaced');});
 await check('Direction and scope change actual session query',async()=>{await reset('search');await page.click('[data-direction="experience"]');await page.click('[data-action="scopes"]');await page.uncheck('[data-field="scope"][value="public"]');const v=await view();assert(v.query.direction==='experience'&&!v.query.scopes.includes('public'),'query did not update');await page.keyboard.press('Escape');assert(await page.locator('.compare-scopes-popover').isHidden(),'Escape did not close scopes');});
 await check('Blank query cannot submit',async()=>{await reset('search');await page.fill('[data-field="question"]','  ');assert(await page.locator('[data-search-submit]').isDisabled(),'empty query allowed');});
 await check('Unavailable local scope renders honest empty state',async()=>{await reset('search');await page.click('[data-action="scopes"]');await page.uncheck('[data-field="scope"][value="prior"]');await page.uncheck('[data-field="scope"][value="public"]');await page.check('[data-field="scope"][value="authorized"]');await page.keyboard.press('Escape');await page.click('[data-search-submit]');assert((await view()).candidates.length===0&&await page.locator('.compare-empty').isVisible(),'fake matching candidates');});
 await check('Open candidate and inspect local context/info without external URL',async()=>{await reset('candidates');await page.click('[data-action="open-candidate"]');assert((await view()).screen==='compare','not compare');await page.click('[data-action="context"]');assert((await page.locator('.compare-source-context').textContent()).includes('本地演示'),'wrong context');await page.keyboard.press('Escape');await page.click('[data-action="material-info"]');assert((await page.locator('[data-modal="kind"]').textContent())==='演示材料','wrong material kind');await page.keyboard.press('Escape');});
 await check('Candidate-specific note drafts remain separate and recover',async()=>{await reset('candidates');await page.locator('[data-action="open-candidate"]').nth(0).click();await page.fill('[data-field="comparisonDraft"]','第一份材料的判断');await page.click('[data-action="back-candidates"]');await page.locator('[data-action="open-candidate"]').nth(1).click();assert(await page.inputValue('[data-field="comparisonDraft"]')==='','draft crossed candidate');await page.fill('[data-field="comparisonDraft"]','第二份材料的判断');await page.click('[data-action="back-candidates"]');await page.locator('[data-action="open-candidate"]').nth(0).click();assert(await page.inputValue('[data-field="comparisonDraft"]')==='第一份材料的判断','draft did not recover');});
 await check('Saving user comparison is not understanding mutation',async()=>{await reset('compare');const before=await host();await page.fill('[data-field="comparisonDraft"]','只是我的判断，不等于改理解');await page.click('[aria-label="保存这次判断"]');const after=await host();assert(after.understanding===before.understanding&&after.version===before.version&&after.links.length===0,'note mutated host');});
 await check('Cancel revision with Escape leaves host untouched',async()=>{await reset('compare');const before=await host();await page.click('[data-action="revision"]');await page.fill('[data-field="revision"]','尚未确认的表达');await page.keyboard.press('Escape');assert(!(await view()).revision.open&&JSON.stringify(before)===JSON.stringify(await host()),'cancel mutated host');});
 await check('LINK opens relationship confirmation; host link preserves understanding',async()=>{await reset('compare');const before=await host();await page.click('[data-action="link"]');assert(await page.locator('dialog').isVisible(),'link confirmation absent');assert((await host()).links.length===0,'optimistic link');await page.selectOption('[data-field="relation"]','limitation');await page.click('[data-action="confirm-link"]');const after=await host();const v=await view();assert(after.links.length===1&&after.understanding===before.understanding&&after.version===before.version&&v.screen==='compare','link incorrectly revised understanding');assert(await page.locator('[data-action="reject"]').isDisabled(),'linked candidate can be rejected');});
 await check('Revision requires changed text and explicit before/after confirmation',async()=>{await reset('compare');const before=await host();await page.click('[data-action="revision"]');assert(await page.locator('[data-action="confirm-revision"]').isDisabled(),'unchanged revision permitted');await page.fill('[data-field="revision"]','留下个人表达可能有帮助，但不是唯一方式。');assert((await host()).version===before.version,'draft prematurely mutated host');assert((await page.locator('[data-modal="before"]').textContent())===before.focus.text,'before mismatch');assert((await page.locator('[data-modal="after"]').textContent())==='留下个人表达可能有帮助，但不是唯一方式。','after mismatch');if(capture)await page.screenshot({path:path.join(output,`${prefix}-revision-confirmation.png`)});await page.click('[data-action="confirm-revision"]');const v=await view();const after=await host();assert(v.screen==='returned'&&v.receipt&&after.version===before.version+1&&after.understanding==='留下个人表达可能有帮助，但不是唯一方式。','no authoritative revision');});
 await check('Undo only reverts revision and preserves linked material',async()=>{const before=await host();await page.click('[data-action="undo"]');const after=await host();assert(after.understanding==='收藏时必须留下自己的表达，之后才能接回来。'&&after.links.length===before.links.length,'undo lost source or wrong target');});
 await check('Pending host commit never renders updated screen',async()=>{await reset('compare');await page.evaluate(()=>window.compareFixture.setAutoCommit(false));await page.click('[data-action="revision"]');await page.fill('[data-field="revision"]','只在宿主确认后写回');await page.click('[data-action="confirm-revision"]');assert((await view()).screen==='compare'&&(await host()).version===1,'optimistic updated state');assert(await page.locator('[data-action="confirm-revision"]').isDisabled(),'pending resubmission allowed');await page.evaluate(()=>{window.compareFixture.applyPending();window.compareFixture.setAutoCommit(true);});assert((await view()).screen==='returned','host result not consumed');});
 await check('Stale host version refuses overwrite and does not show returned',async()=>{await reset('compare');await page.click('[data-action="revision"]');await page.fill('[data-field="revision"]','过期草稿');await page.evaluate(()=>window.compareFixture.hostEdit('宿主已经有了后来的编辑'));await page.click('[data-action="confirm-revision"]');assert((await view()).screen==='compare'&&(await host()).understanding==='宿主已经有了后来的编辑','conflict overwrote host');await page.keyboard.press('Escape');});
 await check('User-pasted material is literal text, labelled user, no fake remote link',async()=>{await reset('search');await page.click('[data-action="import"]');await page.fill('[name="title"]','<img src=x onerror=alert(1)>');await page.fill('[name="excerpt"]','<script>window.pwned=true</script> 自己的摘录');await page.fill('[name="context"]','明确粘贴的上下文');await page.click('form[data-form="import"] [type="submit"]');const v=await view();assert(v.candidates.some(c=>c.kind==='user'&&c.url===null),'user kind missing');assert(!await page.evaluate(()=>window.pwned),'HTML executed');});
 await check('Return/continue/all use host callbacks without changing matter',async()=>{await reset('returned');const before=await host();await page.click('[data-action="continue"]');await page.click('.compare-top-return');await page.click('.compare-next-actions [data-action="return"]');const log=await page.evaluate(()=>window.compareFixture.log);const after=await host();assert(['onContinue','onAll','onReturn'].every(n=>log.some(e=>e.callback===n))&&JSON.stringify(before)===JSON.stringify(after),'callback missing or matter changed');});
 await check('Compact viewport reflows without horizontal overflow and bottom actions reachable',async()=>{await page.setViewportSize({width:880,height:700});await reset('compare');if(capture)await page.screenshot({path:path.join(output,`${prefix}-compact.png`),fullPage:true});assert(await page.evaluate(()=>document.getElementById('app').scrollWidth<=document.getElementById('app').clientWidth+1),'compact overflow');await page.locator('[data-action="revision"]').scrollIntoViewIfNeeded();await page.click('[data-action="revision"]');assert(await page.locator('dialog').isVisible(),'compact action inaccessible');await page.keyboard.press('Escape');await page.setViewportSize({width:1672,height:941});});
 await check('390px viewport keeps native dialog and source actions reachable',async()=>{await page.setViewportSize({width:390,height:844});await reset('compare');assert(await page.evaluate(()=>document.getElementById('app').scrollWidth<=document.getElementById('app').clientWidth+1),'small-screen overflow');await page.locator('[data-action="revision"]').scrollIntoViewIfNeeded();await page.click('[data-action="revision"]');assert(await page.locator('dialog').isVisible(),'dialog not reachable');await page.fill('[data-field="revision"]','窄屏确认的局部表达');await page.locator('[data-action="confirm-revision"]').scrollIntoViewIfNeeded();await page.click('[data-action="confirm-revision"]');assert((await view()).screen==='returned','narrow-screen commit inaccessible');await page.setViewportSize({width:1672,height:941});});
 await check('Long literal excerpts scroll rather than overlap source actions',async()=>{await reset('compare');await page.evaluate(()=>{const v=window.compareFixture.view;v.selectedCandidate.excerpt='<img> 长摘录。'.repeat(150);v.matter.focus.text='长期仍在变化的理解。'.repeat(80);window.compareFixture.injectView(v);});const geometry=await page.evaluate(()=>{const q=document.querySelector('.compare-source blockquote');const action=document.querySelector('.compare-source-actions');return{scroll:q.scrollHeight>q.clientHeight,quoteBottom:q.getBoundingClientRect().bottom,actionsTop:action.getBoundingClientRect().top,html:q.querySelectorAll('img').length};});assert(geometry.scroll&&geometry.quoteBottom<=geometry.actionsTop&&geometry.html===0,'long content escaped bounds');});
 await check('Long candidate titles scroll inside the card without clipping its action',async()=>{await reset('candidates');await page.evaluate(()=>{const v=window.compareFixture.view;v.candidates.forEach(c=>{c.title='用户带入的很长标题。'.repeat(24);c.summary='长材料摘要。'.repeat(100);});window.compareFixture.injectView(v);});const rows=await page.evaluate(()=>[...document.querySelectorAll('.compare-candidate')].map(el=>{const heading=el.querySelector('.compare-candidate-head');const button=el.querySelector('button');return{scroll:heading.scrollHeight>heading.clientHeight,buttonBottom:button.getBoundingClientRect().bottom,cardBottom:el.getBoundingClientRect().bottom};}));assert(rows.every(row=>row.scroll&&row.buttonBottom<=row.cardBottom),'long title hid action');});
 await check('Destroy removes UI and event handlers',async()=>{await page.evaluate(()=>window.compareFixture.destroy());assert(await page.locator('#app > *').count()===0,'UI remains after destroy');});
})().catch(error=>{report.fatal=error.stack;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));report.serverStopped=true;report.passed=report.checks.filter(c=>c.ok).length;report.total=report.checks.length;fs.writeFileSync(path.join(output,`${prefix}-report.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exitCode=report.fatal||report.passed!==report.total||report.errors.length||report.badResponses.length?1:0;});
