const {chromium}=require('C:/Users/HoSheil/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const workspace=path.resolve(__dirname,'../../..');
const prefix=process.argv[2]||'first';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.woff2':'font/woff2','.json':'application/json; charset=utf-8'};
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(workspace,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));}catch{res.writeHead(400).end();return;}if(!file.startsWith(workspace+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'}).end(data);});});
const report={screens:[],checks:[],pageErrors:[],consoleErrors:[],failedRequests:[]};
async function check(name,fn){try{const value=await fn();if(value===false)throw new Error('false');report.checks.push({name,pass:true,value});}catch(error){report.checks.push({name,pass:false,error:String(error)});}}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:'D:/AGeneral Workspace/xjch2026/wshuzhilv/.playwright-browsers/chromium-1234/chrome-win64/chrome.exe'});try{const page=await browser.newPage({viewport:{width:1672,height:941},reducedMotion:'reduce'});page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.failedRequests.push({url:r.url(),status:r.status()});});await page.goto(`http://127.0.0.1:${server.address().port}/artifacts/trace-one-thing-v1-20260915/ui/fixture.html`);await page.waitForFunction(()=>!!window.fixture);await page.evaluate(()=>document.fonts.ready);
for(const screen of ['reading','resume','discussion','comparison','understanding','paused','reentry','handoff','work','results','revised']){await page.evaluate(s=>window.fixture.set(s),screen);await page.waitForTimeout(450);await page.screenshot({path:path.join(__dirname,`${prefix}-${screen}.png`)});report.screens.push(await page.evaluate(()=>({screen:window.fixture.view.screen,fontSerif:document.fonts.check('22px "Trace Chain Serif"'),fontSans:document.fonts.check('19px "Trace Chain Sans"'),buttonsOutside:[...document.querySelectorAll('main button:not([disabled])')].filter(b=>{const r=b.getBoundingClientRect();return r.bottom>941||r.top<0||r.right>1672||r.left<0}).map(b=>b.dataset.action),horizontalOverflow:[...document.querySelectorAll('.chain-panel,.chain-comparison-main,.chain-handoff-side,.chain-results-panel')].filter(e=>e.scrollWidth>e.clientWidth+3).map(e=>e.className)})));}
await check('active understanding DOM identity and caret survive reducer updates',async()=>{await page.evaluate(()=>fixture.set('understanding'));const e=page.locator('[data-field="understanding"]');await e.focus();await page.evaluate(()=>{window.editorBefore=document.querySelector('[data-field="understanding"]');editorBefore.setSelectionRange(3,3)});await page.keyboard.insertText('真实编辑');return page.evaluate(()=>editorBefore===document.querySelector('[data-field="understanding"]')&&document.activeElement===editorBefore&&fixture.view.matter.understandingDraft.includes('真实编辑')&&editorBefore.selectionStart===7)});
await check('composition Enter does not SEND',async()=>{await page.evaluate(()=>fixture.set('discussion'));await page.locator('[data-field="composer"]').fill('输入法中');return page.evaluate(()=>{const e=document.querySelector('[data-field="composer"]');const before=fixture.actions.filter(a=>a.type==='SEND').length;e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,isComposing:true}));e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));return fixture.actions.filter(a=>a.type==='SEND').length===before})});
await check('empty capture disabled',async()=>{await page.evaluate(()=>fixture.empty());return await page.locator('[data-action="capture-leave"]').isDisabled()});
await check('article selection remains separate from personal expression',async()=>{await page.evaluate(()=>{const e=document.querySelector('[data-selection="article"] p').firstChild;const range=document.createRange();range.setStart(e,0);range.setEnd(e,14);const s=getSelection();s.removeAllRanges();s.addRange(range);e.parentElement.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});await page.locator('[data-field="capture"]').fill('我的个人问题');await page.locator('[data-action="capture-discuss"]').click();return page.evaluate(()=>fixture.view.matter.originalText==='我们每个人都会收藏一些内容。'&&fixture.view.matter.whyCare==='我的个人问题')});
await check('narrow loop capture edit save collapse reopen handoff result revision',async()=>{await page.evaluate(()=>fixture.action({type:'NAVIGATE',screen:'understanding'}));await page.locator('[data-field="understanding"]').fill('局部原句，保持其它内容。');await page.locator('[data-field="stop"]').fill('还有什么条件？');await page.locator('[data-action="save-understanding"]').click();await page.locator('[data-action="collapse"]').click();await page.locator('.chain-matter-bubble').click();if(await page.evaluate(()=>fixture.view.screen==='reentry'))await page.locator('[data-action="resume"]').click();if(await page.evaluate(()=>fixture.view.screen!=='understanding'))await page.locator('[data-action="understanding"]').click();await page.locator('[data-action="handoff"]').click();await page.locator('[data-action="confirm-handoff"]').click();await page.locator('[data-action="results"]').click();await page.locator('[data-field="result-fact"]').fill('实际带回的事实');await page.locator('[data-field="result-interpretation"]').fill('还只是我的解释');await page.locator('[data-field="result-unconfirmed"]').fill('还需下一次观察');await page.locator('[data-field="result-understanding"]').fill('这一次修订后的理解。');await page.locator('[data-action="commit-revision"]').click();const id=await page.evaluate(()=>fixture.view.selectedId);await page.locator('[data-action="collapse"]').click();await page.locator('.chain-matter-bubble').click();return page.evaluate(id=>fixture.view.selectedId===id&&fixture.view.matter.understanding==='这一次修订后的理解。'&&fixture.view.matter.results[0].fact==='实际带回的事实',id)});
await check('local suggestion exact selection, acceptance and undo',async()=>{await page.evaluate(()=>fixture.set('understanding'));await page.locator('[data-action="dismiss-suggestion"]').click();const before=await page.locator('[data-field="understanding"]').inputValue();await page.evaluate(()=>{const e=document.querySelector('[data-field="understanding"]');e.focus();e.setSelectionRange(0,5);e.dispatchEvent(new Event('select',{bubbles:true}));});await page.locator('[data-action="suggest"]').click();await page.locator('[data-field="suggestion-draft"]').fill('我的修订');await page.locator('[data-action="create-suggestion"]').click();await page.locator('[data-action="accept-suggestion"]').click();const after=await page.locator('[data-field="understanding"]').inputValue();await page.locator('[data-action="undo-suggestion"]').click();return after==='我的修订'+before.slice(5)&&(await page.locator('[data-field="understanding"]').inputValue())===before;});
await check('result-only never revises understanding',async()=>{await page.evaluate(()=>fixture.set('results'));const before=await page.evaluate(()=>fixture.view.matter.understanding);await page.locator('[data-action="keep-result"]').click();return page.evaluate(before=>fixture.view.matter.understanding===before&&fixture.view.matter.results.length===1,before)});
await check('rejected new material retained unassigned',async()=>{await page.evaluate(()=>fixture.set('reentry'));const text=await page.locator('[data-field="incoming"]').inputValue();await page.locator('[data-action="incoming-unrelated"]').click();return page.evaluate(text=>fixture.view.unassignedMaterials.some(m=>m.text===text),text)});
await check('fresh context changes text not only styling',async()=>{await page.evaluate(()=>fixture.set('resume'));await page.locator('[data-action="fresh"]').click();return page.evaluate(()=>fixture.view.contextMode==='fresh'&&!fixture.view.context.understanding&&!fixture.view.context.stop)});
await check('HTML user text remains text',async()=>{await page.evaluate(()=>{fixture.empty();fixture.action({type:'CAPTURE_DRAFT',text:'<img src=x onerror="window.injected=true">'});fixture.action({type:'CAPTURE',intent:'discuss'});});return page.evaluate(()=>!window.injected&&!document.querySelector('img[src="x"]'))});
await check('comparison selects real fixture material and limit relation persists',async()=>{await page.evaluate(()=>fixture.set('discussion'));await page.locator('[data-action="comparison"]').click();await page.locator('[data-field="relation"]').selectOption('limitation');return page.evaluate(()=>fixture.view.comparison.sourceId==='source-comparison'&&fixture.view.comparison.relation==='limitation')});
await check('modal focus trap and Esc return focus',async()=>{await page.evaluate(()=>fixture.set('resume'));const trigger=page.locator('[data-action="provenance"]');await trigger.focus();await trigger.click();await page.keyboard.press('Escape');return page.evaluate(()=>!document.querySelector('[role="dialog"]')&&document.activeElement.dataset.action==='provenance')});
await check('formatted discussion exact selection offsets remain valid',async()=>{await page.evaluate(()=>fixture.set('discussion'));return page.evaluate(()=>{const e=document.querySelectorAll('.chain-discussion-block')[2].firstChild;const range=document.createRange();range.setStart(e,0);range.setEnd(e,5);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);e.parentElement.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));const f=fixture.view.focus;return f&&f.text===e.textContent.slice(0,5)&&fixture.view.discussion.text.slice(f.start,f.end)===f.text;})});
await check('fresh discussion does not present old messages',async()=>{await page.evaluate(()=>{fixture.set('resume');fixture.action({type:'FRESH_CONTEXT'});fixture.action({type:'NAVIGATE',screen:'discussion'});});return page.evaluate(()=>!document.querySelector('[data-selection="discussion"]').textContent.includes('第二种好像')&&fixture.view.discussion.cases.length===0)});
await page.setViewportSize({width:1280,height:800});await page.evaluate(()=>fixture.set('results'));await page.screenshot({path:path.join(__dirname,`${prefix}-1280.png`)});await page.setViewportSize({width:880,height:620});await page.evaluate(()=>fixture.set('understanding'));await page.screenshot({path:path.join(__dirname,`${prefix}-880.png`)});
await check('destroy clears mount and listener scope',async()=>page.evaluate(()=>{fixture.destroy();return !document.querySelector('.chain-stage')&&!document.querySelector('#fixture').classList.contains('chain-root')}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));fs.writeFileSync(path.join(__dirname,`${prefix}-checks.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}if(report.checks.some(c=>!c.pass)||report.pageErrors.length)process.exitCode=1;
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
